apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: kubecodex
  repo: https://thecodingsheikh.github.io/helm-charts
  releaseName: kubecodex
  version: 1.0.0
  valuesFile: values.yaml