apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "-2"
  name: network
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: network
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
    - git:
        repoURL: https://github.com/TheCodingSheikh/my-gitops.git
        revision: "HEAD"
        requeueAfterSeconds: 20
        files:
          - path: "apps/*/network/**/config.yaml"
        values:
          cluster: "{{index .path.segments 1}}"
          project: "{{index .path.segments 2}}"
          app_path: "{{.path.path}}"
          name: "{{.path.basename}}"
  template:
    metadata:
      name: '{{ default ( printf "%s-%s" .values.cluster ( .values.app_path | replace "/" "-" | trimPrefix ( printf "apps-%s-%s-" .values.cluster .values.project ) ) ) .appName }}'
      namespace: argocd
    spec:
      destination:
        namespace: '{{ default ( .values.app_path | replace "/" "-" | trimPrefix ( printf "apps-%s-%s-" .values.cluster .values.project ) ) .destNamespace }}'
        name: '{{ default .values.cluster .destServer }}'
      project: '{{.values.project}}'
      source:
        repoURL: '{{ default "https://github.com/TheCodingSheikh/my-gitops.git" .repoURL }}'
        targetRevision: '{{ default "HEAD" .srcTargetRevision }}'
        path: '{{ default .values.app_path .srcPath }}'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        retry:
          limit: 30
          backoff:
            duration: 20s
            factor: 1
            maxDuration: 20s
        syncOptions:
        - CreateNamespace=true
  templatePatch: |
    metadata:
      labels:
        app.kubernetes.io/name: '{{.values.app_path | replace "/" "-" | trimPrefix (printf "apps-%s-%s-" .values.cluster .values.project)}}'
        {{- range $key, $value := .labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      annotations:
        {{- range $key, $value := .annotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
  syncPolicy: {}
