appName: "" # If Empty the Application name will be "in-cluster-sample-app"
destNamespace: "" # If Empty the Application destination namespace will be "sample-app"
destServer: "" # If Empty the Application destination server will be "in-cluster"
repoURL: "" # If Empty the Application source repo will be this repo
srcPath: "" # If Empty the Application source path will be this file's path "apps/in-cluster/project-1/sample-app"
srcTargetRevision: "" # If Empty the Application source target revision will be "HEAD"
labels: {} # Additional Application labels
annotations: {} # Additional Application annotations