apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: trust-manager
  repo: https://charts.jetstack.io
  version: 0.17.1
  includeCRDs: true
  namespace: cert-manager
  releaseName: trust-manager
  valuesFile: values.yaml