apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: kyverno
  repo: https://kyverno.github.io/kyverno
  version: 3.4.1
  includeCRDs: true
  namespace: kyverno
  releaseName: kyverno
