apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterpolicies.kyverno.io
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: policies.kyverno.io
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true