apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  version: v1.14.0
  includeCRDs: true
  namespace: cert-manager
  releaseName: cert-manager
  valuesFile: values.yaml