apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres-operator

helmCharts:
- name: pgo
  repo: oci://registry.developers.crunchydata.com/crunchydata
  version: 5.7.4
  releaseName: pgo
  includeCRDs: true
  namespace: postgres-operator
