apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: keycloak
  repo: oci://registry-1.docker.io/bitnamicharts
  version: 24.4.3
  valuesFile: values.yaml
  releaseName: keycloak
  namespace: keycloak