apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: vault-unseal
  repo: https://babykart.github.io/vault-unseal
  version: 0.7.0
  includeCRDs: true
  namespace: vault
  releaseName: vault-unseal
